on:
  push:
    branches: [main]
  pull_request:
name: Build
jobs:   
  flatpak:
    name: "Build Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: ticketbooth-devel.flatpak
        manifest-path: me.iepure.Ticketbooth.Devel.json
        cache-key: flatpak-builder-${{ github.sha }}
